image: gradle:8.5-jdk17

variables:
  DOCKER_IMAGE: trojancodes/springboot_api
  VERSION: $CI_COMMIT_SHORT_SHA
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/
    - build/

stages:
  - build
  - test
  - package
  - deploy-dev

build:
  stage: build
  script:
    - gradle clean assemble
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/
    expire_in: 1 week

package:
  stage: package
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
  script:
    # Login to Docker Hub
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    # Build and push Docker image
    - docker build -t ${DOCKER_IMAGE}:${VERSION} -t ${DOCKER_IMAGE}:latest .
    - docker push ${DOCKER_IMAGE}:${VERSION}
    - docker push ${DOCKER_IMAGE}:latest
  only:
    - main
    - tags